### ISSUE TITLE
初步怀疑是版本号的原因，我分别尝试4.2.4、4.0.16均提示以下session错误，配置文件无误，初始化时可以建集合，debug时获取用户名密码正常

### ISSUE THREAD

**Issue by sampsongi** [jimmyzhong/sofa-dashboard#4]
2020-03-13 12:06:02.725  INFO 4880 --- [0.0-8800-exec-3] a.s.s.m.AbstractValidatingSessionManager : Enabling session validation scheduler...
2020-03-13 12:06:03.435  INFO 4880 --- [schedule-pool-1] sys-user                                 : [127.0.0.1]内网IP[admin][SUCCESS][登录成功]
2020-03-13 12:06:03.445  INFO 4880 --- [0.0-8800-exec-3] m.i.dashboard.manage.security.UserRealm  : 对用户[admin]进行登录验证..验证未通过Sessions are not supported by the MongoDB cluster to which this client is connected
2020-03-13 12:06:03.461 ERROR 4880 --- [schedule-pool-1] m.i.dashboard.manage.util.ThreadUtil     : Sessions are not supported by the MongoDB cluster to which this client is connected

com.mongodb.MongoClientException: Sessions are not supported by the MongoDB cluster to which this client is connected
	at com.mongodb.MongoClient.startSession(MongoClient.java:560) ~[mongodb-driver-3.8.2.jar:na]
	at org.springframework.data.mongodb.core.SimpleMongoDbFactory.getSession(SimpleMongoDbFactory.java:87) ~[spring-data-mongodb-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.data.mongodb.MongoTransactionManager.newResourceHolder(MongoTransactionManager.java:349) ~[spring-data-mongodb-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.data.mongodb.MongoTransactionManager.doBegin(MongoTransactionManager.java:138) ~[spring-data-mongodb-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:474) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:289) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at me.izhong.dashboard.manage.service.impl.SysLoginInfoServiceImpl$$EnhancerBySpringCGLIB$$24ec929d.insert(<generated>) ~[classes/:na]
	at me.izhong.dashboard.manage.factory.AsyncFactory$2.run(AsyncFactory.java:74) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

**Comment by sampsongi** [comment]
可能是多副本的原因，先试试
